deploy-script-test: &deploy-script-test
  script:
    - git submodule update --init --recursive --remote
    - DOCKER_TAG_TEST=$(cat docker-tag-test)
    - sh pipelines/deploy.sh ${BITBUCKET_DEPLOYMENT_ENVIRONMENT} ${DOCKER_TAG_TEST}
    - sh pipelines/deploy-wait.sh ${BITBUCKET_DEPLOYMENT_ENVIRONMENT} ${DOCKER_TAG_TEST}

steps:
  - build: &build
      name: build
      image: linktimelabs/docker-build-kotlin-fullstack:latest
      caches:
        - gradle
        - node
      script:
        - gradle clean updateBuildVersion build -DbuildVersion="$BITBUCKET_COMMIT"
      artifacts:
        - build/**
        - backend/build/**
        - frontend/build/**

  - docker: &docker-build-push
      name: docker-build-push
      image: tstrohmeier/awscli:3.7.2
      script:
        - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
        - export DOCKER_TAG_TEST=$(echo "test-$BITBUCKET_COMMIT_SHORT-$BITBUCKET_BUILD_NUMBER")
        - sh pipelines/docker-build-push-aws.sh latest ${DOCKER_TAG_TEST}
        - echo "${DOCKER_TAG_TEST}" > docker-tag-test
      services:
        - docker
      artifacts:
        - docker-tag-test

  - deploy-test-auto: &deploy-test-auto
      name: deploy-test-auto
      image: tstrohmeier/awscli:3.7.2
      deployment: test
      <<: *deploy-script-test

  - deploy-test-manual: &deploy-test-manual
      name: deploy-test-manual
      image: tstrohmeier/awscli:3.7.2
      trigger: manual
      deployment: test
      <<: *deploy-script-test

  - deploy-prod-manual: &deploy-prod-manual
      name: deploy-prod-manual
      image: tstrohmeier/awscli:3.7.2
      trigger: manual
      deployment: prod
      script:
        - git submodule update --init --recursive --remote
        - DOCKER_TAG_TEST=$(cat docker-tag-test)
        - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
        - export DOCKER_TAG_PROD=$(echo "prod-$BITBUCKET_COMMIT_SHORT-$BITBUCKET_BUILD_NUMBER")
        - sh pipelines/docker-tag-push-aws.sh ${DOCKER_TAG_TEST} ${DOCKER_TAG_PROD}
        - sh pipelines/deploy.sh ${BITBUCKET_DEPLOYMENT_ENVIRONMENT} ${DOCKER_TAG_PROD}
      services:
        - docker


pipelines:

  default:
    - step: *build
    - step: *docker-build-push
    - step: *deploy-test-manual

  branches:
    master:
      - step: *build
      - step: *docker-build-push
      - step: *deploy-test-auto
      - step: *deploy-prod-manual
