deploy-script-test: &deploy-script-test
  script:
    - DOCKER_TAG_TEST=$(cat docker-tag-test)
    - sh pipelines/deploy.sh ${BITBUCKET_DEPLOYMENT_ENVIRONMENT} ${DOCKER_TAG_TEST}
    - sh pipelines/deploy-wait.sh ${BITBUCKET_DEPLOYMENT_ENVIRONMENT} ${DOCKER_TAG_TEST}

steps:
  - build: &build
      name: build
      image: atlassian/default-image:2
      caches:
        - gradle
        - node
      script:
        - COMMIT_MESSAGE=`git log --format=%B -n 1 $BITBUCKET_COMMIT`
        - case $COMMIT_MESSAGE in "[skip build]"*) true;; *)
          ./gradlew clean updateBuildVersion build -DbuildVersion="$BITBUCKET_COMMIT"
          ;;
          esac
      artifacts:
        - build/**
        - backend/build/**
        - frontend/build/**

  - docker-build-push: &docker-build-push
      name: docker-build-push
      image: atlassian/pipelines-awscli:latest
      script:
        - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
        - export DOCKER_TAG_TEST=$(echo "test-$BITBUCKET_COMMIT_SHORT-$BITBUCKET_BUILD_NUMBER")
        - COMMIT_MESSAGE=`git log --format=%B -n 1 $BITBUCKET_COMMIT`
        - case
          $COMMIT_MESSAGE in "[skip build]"*) sh pipelines/docker-tag-push-aws.sh latest ${DOCKER_TAG_TEST};;
          *) sh pipelines/docker-build-push-aws.sh latest ${DOCKER_TAG_TEST};;
          esac
        - echo "${DOCKER_TAG_TEST}" > docker-tag-test
      services:
        - docker
      artifacts:
        - docker-tag-test

  - deploy-test-auto: &deploy-test-auto
      name: deploy-test-auto
      image: atlassian/pipelines-awscli:latest
      deployment: Test
      <<: *deploy-script-test

  - deploy-test-manual: &deploy-test-manual
      name: deploy-test-manual
      image: atlassian/pipelines-awscli:latest
      trigger: manual
      deployment: Test
      <<: *deploy-script-test

  - deploy-prod-manual: &deploy-prod-manual
      name: deploy-prod-manual
      image: atlassian/pipelines-awscli:latest
      trigger: manual
      deployment: Prod
      script:
        - DOCKER_TAG_TEST=$(cat docker-tag-test)
        - export BITBUCKET_COMMIT_SHORT=$(echo $BITBUCKET_COMMIT | cut -c1-7)
        - export DOCKER_TAG_PROD=$(echo "prod-$BITBUCKET_COMMIT_SHORT-$BITBUCKET_BUILD_NUMBER")
        - sh pipelines/docker-tag-push-aws.sh ${DOCKER_TAG_TEST} ${DOCKER_TAG_PROD}
        - sh pipelines/deploy.sh ${BITBUCKET_DEPLOYMENT_ENVIRONMENT} ${DOCKER_TAG_PROD}
      services:
        - docker


pipelines:

  default:
    - step: *build
    - step: *docker-build-push
    - step: *deploy-test-manual

  branches:
    master:
      - step: *build
      - step: *docker-build-push
      - step: *deploy-test-auto
      - step: *deploy-prod-manual
