name: KtorBase

on: [ push ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-ktorbase
          restore-keys: |
            ${{ runner.os }}-gradle-

      # ktor prevents compile-time 11, see: https://youtrack.jetbrains.com/issue/KTOR-619
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Gradle Build
        run: ./gradlew build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: linkedplanet/ktorbase:latest


  docker-integration-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Start KtorBase
        run: docker run -d -p 9090:9090 -e APPLICATION_SECRET=0000000000000000000000000000000 linkedplanet/ktorbase:latest

      - name: Await Start-up
        run: wget --tries 10 http://localhost:9090/health

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-ktorbase
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Integration Tests
        run: ./gradlew integrationTest
