name: KtorBase-Bitbucket-Example

on:
  push:
    branches:
      - master

jobs:

  update-bitbucket-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-example-ktorbase-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-example-ktorbase-

      # ktor prevents compile-time 11, see: https://youtrack.jetbrains.com/issue/KTOR-619
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          name: id_rsa
          key: ${{ secrets.BITBUCKET_SSH_KEY }}
          known_hosts: ${{ secrets.BITBUCKET_KNOWN_HOSTS }}

      - name: Clone from Bitbucket
        run: >
          git clone https://bitbucket.org/linked-planet/ktorbase-bitbucket-example.git

      - name: Update
        run: >
          BRANCH=${GITHUB_REF#refs/heads/};
          curl -O -s "https://raw.githubusercontent.com/linked-planet/ktorbase/$BRANCH/update.sh";
          sh ./update.sh ./com.linked-planet.ktor-bitbucket-example com.linked-planet ktor-bitbucket-example "$BRANCH"

      - name: Commit and Push to Bitbucket
        run: |
          cd com.linked-planet.ktor-bitbucket-example;
          git config --global user.email "${{ secrets.BITBUCKET_USER_MAIL }}";
          git config --global user.name "${{ secrets.BITBUCKET_USER_NAME }}";
          git commit -m "updated project from Github commit ${{ env.GITHUB_SHA }} (${{ env.GITHUB_REF }})";
          git push
